### PR TITLE
Update index.html

### PR DESCRIPTION
**Pull request by Mebin-Abraham**
Mebin Abraham

### CODE REVIEW

**Comment by mebin31072002** [comment]
Mebin Abraham

**Comment by madhavbiju** [comment]
Kindly upload screenshot too

**Review by Mebin-Abraham — COMMENTED** [review]
added name

**Comment by Mebin-Abraham** [comment]
Mebin Abraham

**Comment by Mebin-Abraham** [comment]
Hi bro,

I have uploaded the screenshot. If there's anything else please let me know.

Thanking you,
Yours sincerely,
Mebin Abraham

**Pull request merged**
